import type { Metadata } from "next";
import { Archivo as DisplayFont } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import Sidebar from "@/components/navbar/sidebar/Sidebar";
import TopNavBar from "@/components/navbar/TopNavBar";
import RootLayoutProvider from "@/providers/RootLayoutProvider";
import Footer from "@/components/footer/Footer";
import AnimateProvider from "@/providers/AnimateProvider";
import DailyClaimModal from "@/modules/DailyClaimModal";
import "./globals.css";
import LoadingScreen from "@/modules/LoadingScreen";

const font = DisplayFont({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Aptos Gamble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const google_analytics_id = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

  return (
    <html>
      <body className={`${font.className} bg-primary transition`}>
        <RootLayoutProvider>
          <TopNavBar />
          <Sidebar />
          <div className="overflow-y-scroll h-[calc(100vh-4.5rem)]">
            <AnimateProvider>{children}</AnimateProvider>
            <Footer />
          </div>
          <DailyClaimModal />
          <LoadingScreen />
        </RootLayoutProvider>
        {google_analytics_id && <GoogleAnalytics gaId={google_analytics_id} />}
      </body>
    </html>
  );
}
